version: 2
jobs:
  ## Build & Deploy against development backend
  "build-dev":
    docker:
      - image: docker:18.06.0-ce-git
    steps:
      # Initialization.
      - checkout
      - setup_remote_docker
      - run:
          name: Installation of build dependencies.
          command: |
            apk add --no-cache bash
            apk add --no-cache jq py-pip sudo curl
            pip install --upgrade pip
            sudo pip install awscli --upgrade
            sudo curl -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
            sudo pip install docker-compose
            sudo chmod +x /usr/local/bin/ecs-cli
      - run:
          name: Executing build.
        #  command: |
        #    chmod +x build.sh
        #    ./build.sh DEV
             pwd
      - deploy:
          name: Running Masterscript.
          command: |
            git clone --branch devsts https://github.com/topcoder-platform/tc-deploy-scripts ../buildscript
            cp ./../buildscript/master_deploy.sh .
            cp ./../buildscript/buildenv.sh .
            cp ./../buildscript/awsconfiguration.sh .
            ./awsconfiguration.sh DEV
            source awsenvconf      
            chmod +x build.sh
            ./build.sh DEV
            ./buildenv.sh -e DEV -b submission-scoring-processor_deployvar
            source buildenvvar
            ./master_deploy.sh -d ECS -e DEV -t $CIRCLE_SHA1 -s submission-scoring-processor_appvar
          #command: |
          #  git clone --branch master https://github.com/topcoder-platform/tc-deploy-scripts ../buildscript
          #  cp ./../buildscript/master_deply_v4.2.sh .
          #  ./master_deply_v4.2.sh -d ECS -e DEV -t $CIRCLE_BUILD_NUM -s submission-scoring-processor
    
  "build-prod":
    docker:
      - image: docker:18.06.0-ce-git
    steps:
      # Initialization.
      - checkout
      - setup_remote_docker
      - run:
          name: Installation of build dependencies.
          command: |
            apk add --no-cache bash
            apk add --no-cache jq py-pip sudo curl
            pip install --upgrade pip
            sudo pip install awscli --upgrade
            sudo curl -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
            sudo pip install docker-compose
            sudo chmod +x /usr/local/bin/ecs-cli
      - run:
          name: Executing build.
          command: 
             chmod +x build.sh
             ./build.sh PROD
      - deploy:
          name: Running Masterscript.
          command: |
            git clone --branch devsts https://github.com/topcoder-platform/tc-deploy-scripts ../buildscript
            cp ./../buildscript/master_deploy.sh .
            cp ./../buildscript/buildenv.sh .
            cp ./../buildscript/awsconfiguration.sh .
            ./awsconfiguration.sh DEV
            source awsenvconf            
            ./buildenv.sh -e DEV -b submission-scoring-processor_deployvar
            source buildenvvar
            ./master_deploy.sh -d ECS -e DEV -t $CIRCLE_SHA1 -s submission-scoring-processor_appvar
workflows:
  version: 2
  build:
    jobs:
      # Development builds are executed on "develop" branch only.
      - "build-dev":
          context : org-global
          filters:
            branches:
              only: [ "develop", "dev-circleci" ]
      - "build-prod":
          filters:
            branches:
              only: master1
