version: '3'
services:
  submission-scoring-processor:
    image: submission-scoring-processor:latest
    build:
      context: ../
      dockerfile: docker/Dockerfile
    env_file:
      - api.env
    network_mode: "host"
